### PR TITLE
Fix infinite symbolic links

### PR DESCRIPTION
**Pull request by edwardloveall**
We're using filter_builder in CI by installing it into `vendor/bundle` via bundlers `--path=` option along with other gems. Sometimes loading the app will cause in infinite loop. This is because the `spec/dummy/spec` path is a symbolic link to `../../spec`. So ruby goes to load `/spec`, which loads `/spec/dummy`, which loads `/spec/dummy/spec` which loads `/spec` again.

This fixes the issue by:

- Removing the `/spec/dummy/spec` symbolic link
- Moving the fabricators to `/spec/dummy/spec/fabricators` so they can be found by the test suite

### CODE REVIEW

**Comment by heatherbooker** [comment]
Ooh interesting, did this suddenly start happening?

**Comment by edwardloveall** [comment]
> Ooh interesting, did this suddenly start happening?

It does seem that way! I'm not sure why though. The last time we updated our internal circle config (I've only seen this run in circle) was three months ago. Really odd.

**Comment by heatherbooker** [comment]
For posterity, here's a failure with it: https://app.circleci.com/pipelines/github/relevant-healthcare/relevant/14465/workflows/0acbe288-d6a0-4c45-a14b-a4b7ca3a4111/jobs/121584/parallel-runs/0?filterBy=FAILED

Which shows
```
Errno::ELOOP: Too many levels of symbolic links @ dir_initialize - /home/circleci/relevant-healthcare/relevant/vendor/bundle/ruby/3.0.0/bundler/gems/filter_builder-5f0aeb0b85d5/spec/dummy/spec/dummy/spec/dummy/spec/dummy...and so on forever
```

**Review by heatherbooker — APPROVED** [review]
Thanks for doing this fix!

@Tassosb helped me review, with the following input:
- nltx is the current branch, not master
- CI passed, so we know the new fabricators are accessible
- we looked at the failure in CI to understand it

**Pull request merged**
